name: Deploy Docker-react-pod
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t 01919965532/docker-react-pod -f Dockerfile.dev .
      - run: docker run -e CI=true 01919965532/docker-react-pod npm run test -- --coverage

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: react-docker-pod
          environment_name: Reactdockerpod-env
          existing_bucket_name: elasticbeanstalk-us-east-1-863452371063
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
